### ISSUE TITLE
Dialogue does not close on  accept or deny or back button pressed when attempting to enable bluetooth

### ISSUE THREAD

**Issue by nisrulz** [WebBluetoothCG/ble-test-peripheral-android#52]
Device : 
Asus Zenfone 2 ( ASUS_Z00AD)
Custom ROM : SuperZen
OS version : Android 5.0

How to reproduce : 
+  Bluetooth in off state
+  Install app
+  click on battery option
+  prompted with accept or deny to  enable bluetooth
+ cannot exit the prompt from selecting accept, deny or back button on device

![screenshot_2015-11-17-14-53-01](https://cloud.githubusercontent.com/assets/2096087/11227504/3e3acb2a-8d3b-11e5-8836-1771aa60a8b7.jpg)
![screenshot_2015-11-17-14-53-15](https://cloud.githubusercontent.com/assets/2096087/11227505/3e3c1264-8d3b-11e5-8305-50890d9de3e3.jpg)

**Comment by g-ortuno** [comment]
That seems more like a OS issue tbh. But I'll try to get my hands on Zenfone and try it out.

**Comment by nisrulz** [comment]
Retested
Device : Nexus 9, factory image , android os v6.0
Status : Working

Device : Moto G 2013, custom os , cyanogenmod 12.1 osv5.1.1
Status : Working

Most probably issue with custom os SuperZen in Zenfone 2.
