### ISSUE TITLE
MAC Address change every few minutes

### ISSUE THREAD

**Issue by giridhara** [WebBluetoothCG/ble-test-peripheral-android#62]
Hi,

We observe that MAC address of the peripheral is changing every few minutes.
Is it possible to assign fixed MAC address for the peripheral (Battery / Heart Rate Monitor)?

Thanks,
Giridhar.

**Comment by beaufortfrancois** [comment]
I believe private MAC addresses are a feature of Bluetooth 4.2. See http://blog.bluetooth.com/bluetooth-technology-protecting-your-privacy/
According to http://stackoverflow.com/a/28612453/422957, you can't turn off this feature.
