### ISSUE TITLE
Can't subscribe to notifications on macOS & Android

### ISSUE THREAD

**Issue by g-ortuno** [WebBluetoothCG/ble-test-peripheral-android#63]
"One or more parameters were invalid" CoreBluetooth error Code 1.

**Comment by beaufortfrancois** [comment]
This is not specific to macOS. See https://bugs.chromium.org/p/chromium/issues/detail?id=578811#c15 as well.

> 
> I've just tried with the BLE SIM App (version 6.0) on a Nexus 5X and https://googlechrome.github.io/samples/web-bluetooth/notifications.html on a Nexus 5 and I get 'Not Supported' as well sadly.
> From what I understood, https://github.com/WebBluetoothCG/ble-test-peripheral-android/commit/36b1a8ad0a12b3026c43c0df834c9f72dcf81fc3 was supposed to add descriptor to characteristics that support notifications.
> 
> Here are Web Bluetooth client adb logs (Nexus 5):
> 
> 06-22 10:34:42.440 23934 23934 I cr_Bluetooth: connectGatt
> 06-22 10:34:42.441 23934 23934 D BluetoothGatt: connect() - device: 5A:F5:D1:B8:B7:EC, auto: false
> 06-22 10:34:42.441 23934 23934 D BluetoothGatt: registerApp()
> 06-22 10:34:42.441 23934 23934 D BluetoothGatt: registerApp() - UUID=61ac93cb-b3da-4a84-8358-9dac187e856d
> 06-22 10:34:42.441  2137  2196 D BtGatt.GattService: registerClient() - UUID=61ac93cb-b3da-4a84-8358-9dac187e856d
> 06-22 10:34:42.442  2137  2160 D BtGatt.GattService: onClientRegistered() - UUID=61ac93cb-b3da-4a84-8358-9dac187e856d, clientIf=5
> 06-22 10:34:42.442 23934 24764 D BluetoothGatt: onClientRegistered() - status=0 clientIf=5
> 06-22 10:34:42.442  2137  2149 D BtGatt.GattService: clientConnect() - address=5A:F5:D1:B8:B7:EC, isDirect=true
> 06-22 10:34:42.443  2137  2160 D bt_btif_config: btif_get_address_type: Device [5a:f5:d1:b8:b7:ec] address type 1
> 06-22 10:34:42.443  2137  2160 D bt_btif_config: btif_get_device_type: Device [5a:f5:d1:b8:b7:ec] type 2
> 06-22 10:34:42.917  2137  2169 W bt_smp  : smp_br_connect_callback is called on unexpected transport 2
> 06-22 10:34:42.918  2137  2169 W bt_btif : bta_dm_acl_change info: 0x0
> 06-22 10:34:42.918  2137  2160 D bt_btif_dm: remote version info [5a:f5:d1:b8:b7:ec]: 0, 0, 0
> 06-22 10:34:42.918  2137  2160 E BluetoothRemoteDevices: state12newState0
> 06-22 10:34:42.919  2137  2160 D BtGatt.GattService: onConnected() - clientIf=5, connId=5, address=5A:F5:D1:B8:B7:EC
> 06-22 10:34:42.920 23934 24032 D BluetoothGatt: onClientConnectionState() - status=0 clientIf=5 device=5A:F5:D1:B8:B7:EC
> 06-22 10:34:42.920 23934 24032 I cr_Bluetooth: onConnectionStateChange status:0 newState:Connected
> 06-22 10:34:42.920 23934 24032 D BluetoothGatt: discoverServices() - device: 5A:F5:D1:B8:B7:EC
> 06-22 10:34:42.921  2137  2197 D BtGatt.GattService: discoverServices() - address=5A:F5:D1:B8:B7:EC, connId=5
> 06-22 10:34:42.924  1320  1320 I TrustAgent.Tracker: [BluetoothConnectionTracker] Bluetooth connect broadast for Nexus 5X 5A:F5:D1:B8:B7:EC
> 06-22 10:34:43.548  2137  2169 W bt_bta_gattc: bta_gattc_explore_srvc no more services found
> 06-22 10:34:43.548  2137  2160 D BtGatt.GattService: onSearchCompleted() - connId=5, status=0
> 06-22 10:34:43.550 23934 24764 D BluetoothGatt: onSearchComplete() = Device=5A:F5:D1:B8:B7:EC Status=0
> 06-22 10:34:43.550 23934 24764 I cr_Bluetooth: onServicesDiscovered status:0==OK
> 06-22 10:34:43.553 23934 23934 E chromium: [ERROR:bluetooth_remote_gatt_characteristic_android.cc(157)] Found 0 client characteristic configuration descriptors.
> 
> And here are BLE SIM adb logs (Nexus 5X):
> 
> 06-22 10:34:43.881  6313  6313 I WCNSS_FILTER: ibs_msm_serial_clock_vote: vote UART CLK ON using UART driver's ioctl()
> 06-22 10:34:43.884 30745  6323 I bt_btm_ble: btm_ble_resolve_random_addr_on_conn_cmpl unable to match and resolve random address
> 06-22 10:34:43.914 30745  6277 W bt_hci  : filter_incoming_event command complete event with no matching command. opcode: 0x0.
> 06-22 10:34:44.027 30745  6323 W bt_smp  : smp_br_connect_callback is called on unexpected transport 2
> 06-22 10:34:44.030 30745  6323 W bt_btif : bta_dm_acl_change info: 0x0
> 06-22 10:34:44.028 30745 30761 D BtGatt.GattService: onConnected() connId=5, address=6C:48:51:74:BF:4E, connected=true
> 06-22 10:34:44.032 30745 30761 D BtGatt.GattService: onConnected() connId=6, address=6C:48:51:74:BF:4E, connected=true
> 06-22 10:34:44.033 30745 30761 D bt_btif_dm: remote version info [6c:48:51:74:bf:4e]: 0, 0, 0
> 06-22 10:34:44.033  6515  6526 D BluetoothGattServer: onServerConnectionState() - status=0 serverIf=6 device=6C:48:51:74:BF:4E
> 06-22 10:34:44.034 30745 30761 E BluetoothRemoteDevices: aclStateChangeCallback: Device is NULL
> 06-22 10:34:44.034  6515  6526 D BluetoothManager: getConnectedDevices
> 06-22 10:34:44.035 26030 26040 D BluetoothGattServer: onServerConnectionState() - status=0 serverIf=5 device=6C:48:51:74:BF:4E
> 06-22 10:34:44.039 30745 30756 D BtGatt.GattService: getDeviceType() - device=00:21:3C:91:02:C1, type=1
> 06-22 10:34:44.040  6515  6526 V io.github.webbluetoothcg.bletestperipheral.Peripheral: Connected to device: 6C:48:51:74:BF:4E
> 06-22 10:34:44.407 26030 26030 D BluetoothGatt: connect() - device: 6C:48:51:74:BF:4E, auto: false
> 06-22 10:34:44.407 26030 26030 D BluetoothGatt: registerApp()
> 06-22 10:34:44.408 26030 26030 D BluetoothGatt: registerApp() - UUID=b3df59bc-dd63-4ac6-b53d-e16a2659ac37
> 06-22 10:34:44.419 30745 30791 D BtGatt.GattService: registerClient() - UUID=b3df59bc-dd63-4ac6-b53d-e16a2659ac37
> 06-22 10:34:44.420 30745 30761 D BtGatt.GattService: onClientRegistered() - UUID=b3df59bc-dd63-4ac6-b53d-e16a2659ac37, clientIf=8
> 06-22 10:34:44.421 26030 26051 D BluetoothGatt: onClientRegistered() - status=0 clientIf=8
> 06-22 10:34:44.422 30745 30756 D BtGatt.GattService: clientConnect() - address=6C:48:51:74:BF:4E, isDirect=true
> 06-22 10:34:44.425 30745 30761 D BtGatt.GattService: onConnected() - clientIf=8, connId=8, address=6C:48:51:74:BF:4E
> 06-22 10:34:44.426 26030 26041 D BluetoothGatt: onClientConnectionState() - status=0 clientIf=8 device=6C:48:51:74:BF:4E
> 06-22 10:34:44.721 30745  6323 W bt_bta_gattc: bta_gattc_explore_srvc no more services found
> 06-22 10:34:45.093 26030 26030 D BluetoothGatt: discoverServices() - device: 6C:48:51:74:BF:4E
> 06-22 10:34:45.095 30745 30791 D BtGatt.GattService: discoverServices() - address=6C:48:51:74:BF:4E, connId=8
> 06-22 10:34:45.096 30745 30761 D BtGatt.GattService: onSearchCompleted() - connId=8, status=0
> 06-22 10:34:45.098 26030  9801 D BluetoothGatt: onSearchComplete() = Device=6C:48:51:74:BF:4E Status=0

**Comment by monteslu** [comment]
@beaufortfrancois does this mean macos/chromium web bluetooth can subscribe to notifications from other BLE devices?
From the status page it seems that it can't.

**Comment by g-ortuno** [comment]
@monteslu I'm currently reviewing the patch to add support for it :smile:

**Comment by beaufortfrancois** [comment]
Soon, really soon ;)

**Comment by beaufortfrancois** [comment]
For info, I can reproduce the issue with Bluez as well, even though it's more permissive... See

```
< ACL Data TX: Handle 32 flags 0x00 dlen 9                                                                                [hci0] 403.621325
      ATT: Find Information Request (0x04) len 4
        Handle range: 0x002b-0xffff
> HCI Event: Number of Completed Packets (0x13) plen 5                                                                    [hci0] 403.689256
        Num handles: 1
        Handle: 32
        Count: 1
> ACL Data RX: Handle 32 flags 0x02 dlen 9                                                                                [hci0] 403.755926
      ATT: Error Response (0x01) len 4
        Find Information Request (0x04)
        Handle: 0x002b
        Error: Attribute Not Found (0x0a)
```

```	
[Nexus 5X]# list-attributes 
Primary Service
        /org/bluez/hci0/dev_46_EE_57_93_31_08/service0001
        Generic Attribute Profile
Characteristic
        /org/bluez/hci0/dev_46_EE_57_93_31_08/service0001/char0002
        Service Changed
Primary Service
        /org/bluez/hci0/dev_46_EE_57_93_31_08/service0028
        Battery Service
Characteristic
        /org/bluez/hci0/dev_46_EE_57_93_31_08/service0028/char0029
        Battery Level
[Nexus 5X]# select-attribute /org/bluez/hci0/dev_46_EE_57_93_31_08/service0028/char0029
[Nexus 5X:/service0028/char0029]# notify on
[CHG] Attribute /org/bluez/hci0/dev_46_EE_57_93_31_08/service0028/char0029 Notifying: yes
Notify started
[CHG] Attribute /org/bluez/hci0/dev_46_EE_57_93_31_08/service0028/char0029 Value: 0x32
[Nexus 5X:/service0028/char0029]# notify off
[CHG] Attribute /org/bluez/hci0/dev_46_EE_57_93_31_08/service0028/char0029 Notifying: no
Notify stopped

**Comment by beaufortfrancois** [comment]
When running BLE Peripheral Android App from Android Studio, everything works fine. However when using the Android App from Play Store, I can't get notifications to work...
Could it be possible that the play store version is not the same as the one in this repo?

**Comment by beaufortfrancois** [comment]
Uncompiling io.github.webbluetoothcg.bletestperipheral APK from Play Store confirms that this version does NOT include Descriptors fix. I'm not sure why but that explains it...

https://github.com/WebBluetoothCG/ble-test-peripheral-android/commit/2e41b98ebd7776ffb9d28f80620709a9d7e83c1a is in while https://github.com/WebBluetoothCG/ble-test-peripheral-android/commit/36b1a8ad0a12b3026c43c0df834c9f72dcf81fc3 is not ;(

@g-ortuno Do you know what could have happened?
Can you also update Play Store version?

**Comment by beaufortfrancois** [comment]
And I just noticed someone else also reported it at https://play.google.com/store/apps/details?id=io.github.webbluetoothcg.bletestperipheral&reviewId=Z3A6QU9xcFRPR043Q1pDdXRZU0tOTjJmZFFUeXNvbUxLVVRhZWlJTnVYeFYybTRCMmtoQnZfMnBjR19yTzl1M2o1OHN4VUZsZU5MZmtmSUg3bC0zV0otdHc

![screenshot 2016-06-29 at 12 07 52 pm](https://cloud.githubusercontent.com/assets/634478/16448503/2083f1de-3df2-11e6-87b8-c8be6899a4c1.png)

Could we make sure we monitor this Android app comments as well?

**Comment by g-ortuno** [comment]
I sent out an update. This one should include the descriptor.

**Comment by beaufortfrancois** [comment]
@g-ortuno Can you reply to https://play.google.com/store/apps/details?id=io.github.webbluetoothcg.bletestperipheral&reviewId=Z3A6QU9xcFRPR043Q1pDdXRZU0tOTjJmZFFUeXNvbUxLVVRhZWlJTnVYeFYybTRCMmtoQnZfMnBjR19yTzl1M2o1OHN4VUZsZU5MZmtmSUg3bC0zV0otdHc as well?

**Comment by g-ortuno** [comment]
Done
