### ISSUE TITLE
Getting Not Advertising,Advertising data larger than 31 bytes at the start of the application no matter what value i select from slider.

### ISSUE THREAD

**Issue by rajxi** [WebBluetoothCG/ble-test-peripheral-android#68]

**Comment by g-ortuno** [comment]
Could you add some reproduction steps? Also what device are you using? Did you modify any of the code?

**Comment by beaufortfrancois** [comment]
As hinted in http://stackoverflow.com/a/31514794/422957, it may be because we [include](https://github.com/WebBluetoothCG/ble-test-peripheral-android/blob/2e41b98ebd7776ffb9d28f80620709a9d7e83c1a/app/src/main/java/io/github/webbluetoothcg/bletestperipheral/Peripheral.java#L232) Device Name which may be too long there for advertisement data. Should we remove it then?

```diff
     mAdvData = new AdvertiseData.Builder()
-        .setIncludeDeviceName(true)
+        .setIncludeDeviceName(false)
         .setIncludeTxPowerLevel(true)
         .addServiceUuid(mCurrentServiceFragment.getServiceUUID())
         .build();

**Comment by g-ortuno** [comment]
Not sure why we would have to remove it? This is not failing in **our** app is it?

**Comment by beaufortfrancois** [comment]
I'm not able to reproduce but I believe it **would** fail in our app if device name is too long. As we don't control Device Name, the advertisement data included by our app may be too large.

**Comment by g-ortuno** [comment]
I guess we could add some code to warn if the user's device name is too long.

**Comment by beaufortfrancois** [comment]
We could also maybe add a fallback to try without Device name when ADVERTISE_FAILED_DATA_TOO_LARGE is returned and only if that fails, raise an error. WDYT?

**Comment by g-ortuno** [comment]
I think a better alternative would be to calculate the length of the advertising packet before trying to advertise. But I think this is very low priority.

**Comment by beaufortfrancois** [comment]
You're right! `BluetoothAdapter.getDefaultAdapter().getName()` would definitely help us.

**Comment by poshaughnessy** [comment]
Hi, any workarounds for this? I'm getting it on my Samsung S7 Edge (Android 6.0.1):

<img src="https://cloud.githubusercontent.com/assets/151207/20606883/e83803b2-b26b-11e6-8c09-d60227bd6a9b.png" alt="screenshot" width="220px"/>

**Comment by beaufortfrancois** [comment]
I believe https://github.com/WebBluetoothCG/ble-test-peripheral-android/pull/70 should have fixed this. As soon as @g-ortuno pushes master into Play Store, it should work.
In the mean time, you can compile master from source and give it a try.

**Comment by g-ortuno** [comment]
You can also change your phone's name:http://www.phonebuff.com/2012/05/change-android-phones/

**Comment by poshaughnessy** [comment]
@g-ortuno Yeah I tried to look for the setting to change the name briefly earlier, but I don't have the same menus on the Samsung, it looked like it may require rooting.

@beaufortfrancois Ace thanks! Sorry I didn't check master earlier, rushing a bit for my presentation tomorrow. Can confirm it's fixed now I'm compiling from source!

**Comment by g-ortuno** [comment]
Have you tried: http://www.solvemix.com/index.php/android-smartphones/589-samsung-galaxy-s6-how-to-change-device-name-solved ?

**Comment by poshaughnessy** [comment]
Aha yes that helped! For me it's slightly different - just: "About device" - "Device name". Thanks :)
