### ISSUE TITLE
Not able to send more than 20 bytes

### ISSUE THREAD

**Issue by altaf933** [WebBluetoothCG/ble-test-peripheral-android#74]
I tried to send a more than 20 byte(25 bytes) ,it removed after 20 byte values .

**Comment by beaufortfrancois** [comment]
Which service did you use and how did you send more than 20 bytes?

**Comment by altaf933** [comment]
It's **BluetoothGattCharacteristic** service and when I set value more than 20 bytes(U_029E5_X0000_+0000_X1090) in mBatteryLevelCharacteristic.setValue(constantValue) . It removed value after 20 bytes once reach at 20th position(_X1090).

**Comment by beaufortfrancois** [comment]
This is not an issue with the app.
Hopefully http://stackoverflow.com/a/24178409/422957 will help you there.
