### ISSUE TITLE
Notifications not working since last update

### ISSUE THREAD

**Issue by fedekau** [WebBluetoothCG/ble-test-peripheral-android#80]
Hey there,  awesome job with this app, it is really helpful! 😎 

I am the developer of https://github.com/wyeworks/ember-bluetooth and I was using this app to test the addon. Everything was working fine, but since last update from the Play store (the one that added the `Health Thermometer` device) the notifications stopped working for at least the `Battery` device.  I tried this with 3 different devices.

Can anyone confirm that?

**Comment by beaufortfrancois** [comment]
You are right! Here's my adb log:

```
03-21 08:44:11.034 13662 13674 W BluetoothGattServer: Unhandled exception in callback
03-21 08:44:11.034 13662 13674 W BluetoothGattServer: java.lang.UnsupportedOperationException: Method notificationsEnabled not overridden
03-21 08:44:11.034 13662 13674 W BluetoothGattServer:   at io.github.webbluetoothcg.bletestperipheral.ServiceFragment.notificationsEnabled(ServiceFragment.java:64)
03-21 08:44:11.034 13662 13674 W BluetoothGattServer:   at io.github.webbluetoothcg.bletestperipheral.Peripheral$2.onDescriptorWriteRequest(Peripheral.java:219)
03-21 08:44:11.034 13662 13674 W BluetoothGattServer:   at android.bluetooth.BluetoothGattServer$1.onDescriptorWriteRequest(BluetoothGattServer.java:242)
03-21 08:44:11.034 13662 13674 W BluetoothGattServer:   at android.bluetooth.IBluetoothGattServerCallback$Stub.onTransact(IBluetoothGattServerCallback.java:263)
03-21 08:44:11.034 13662 13674 W BluetoothGattServer:   at android.os.Binder.execTransact(Binder.java:565)
```

I'll commit a patch shortly.
Thanks for reporting this issue!

**Comment by beaufortfrancois** [comment]
@g-ortuno Here's how we can fix this:

1. Don't throw errors in https://github.com/WebBluetoothCG/ble-test-peripheral-android/blob/785012e3437615055a3ea3c43c3976fb73307837/app/src/main/java/io/github/webbluetoothcg/bletestperipheral/ServiceFragment.java#L64 and https://github.com/WebBluetoothCG/ble-test-peripheral-android/blob/785012e3437615055a3ea3c43c3976fb73307837/app/src/main/java/io/github/webbluetoothcg/bletestperipheral/ServiceFragment.java#L52
2. Add empty `notificationsEnabled` and `notificationsDisabled` to batteryServiceFragment and heartRateServiceFragment.

Which one do you prefer?

**Comment by g-ortuno** [comment]
What about showing a toast? For example

`Notifications enabled for device: 00:00:00:00:00`

**Comment by beaufortfrancois** [comment]
See PR at https://github.com/WebBluetoothCG/ble-test-peripheral-android/pull/81
