### ISSUE TITLE
mGattServer.sendResponse  return wrong value?

### ISSUE THREAD

**Issue by evstep** [WebBluetoothCG/ble-test-peripheral-android#82]
Hi! 
Possible need to return "status" instead returning GATT_SUCCES?        
```
 status = BluetoothGatt.GATT_SUCCESS;
        descriptor.setValue(value);
      }
      if (responseNeeded) {
        mGattServer.sendResponse(device, requestId, BluetoothGatt.GATT_SUCCESS,
            /* No need to respond with offset */ 0,
            /* No need to respond with a value */ null);
      }
```
[See here](https://github.com/WebBluetoothCG/ble-test-peripheral-android/blob/master/app/src/main/java/io/github/webbluetoothcg/bletestperipheral/Peripheral.java#L230)

**Comment by beaufortfrancois** [comment]
You're right @evstep!
My bad. I've sent https://github.com/WebBluetoothCG/ble-test-peripheral-android/pull/84 to fix this
