### ISSUE TITLE
Feature Request: Custom Defined Services and Identifiers

### ISSUE THREAD

**Issue by ForgeMistress** [WebBluetoothCG/ble-test-peripheral-android#91]
With my current project, I was remiss to find that the options for configuring the services of the simulated BLE peripheral device were lacking. I would love to be able to define devices with custom local names, service definitions with user definable UUIDs (or autogenerated ones) and custom attributes so that I can more fully simulate the devices I will be connecting while I am debugging the code of my central application. This would make debugging points of failure in my peripheral hardware so much easier and put your app miles ahead of the other ones that are on the marketplace.

**Comment by g-ortuno** [comment]
The app was built when there were no apps to simulate BLE peripherals. Nowadays, [nrf Connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en) has pretty much all the feature you could want.
