### ISSUE TITLE
Unsupported device

### ISSUE THREAD

**Issue by Enzo-bianchi** [WebBluetoothCG/ble-test-peripheral-android#92]
I tried your app with this link : https://googlechrome.github.io/samples/web-bluetooth/battery-level-async-await.html
Chrome find my device, but I get unsupported device

```
Requesting Bluetooth Device...
Connecting to GATT Server...
Argh! NetworkError: Unsupported device.
```

I tried with Nrf Connect, but here Chrome don't find my device, I have a oneplus 3

How I can test / simulate BLE with your app ?
Thanks

**Comment by g-ortuno** [comment]
What platform were you using to connect to the device?

**Comment by Enzo-bianchi** [comment]
what do you mean for platform ?

I used the last google Chrome, my Oneplus is on Android 7.1.1, the bluetooth adapter is Asus BT-400 and I am on windows 10

**Comment by g-ortuno** [comment]
Ah, I don't think this app works with Windows sadly 😞 You are going to have to use another Android device, Chrome OS or macOS.
