### ISSUE TITLE
Stuck on Connecting to Gatt Server...

### ISSUE THREAD

**Issue by zuekut** [WebBluetoothCG/ble-test-peripheral-android#94]
Hello,

I tried to read battery level from the battery samples, using the Peripheral Simulator, however after succesfuly pairing my phone, I simply get "Connecting to GATT Server..." without any readings. Thank you in advance! FYI I am using Chrome browser on Windows 10.

**Comment by g-ortuno** [comment]
I believe this is a problem with the Chrome API. You might want to open a bug at http://crbug.com/new
